### ISSUE TITLE
Ukol 1 Hotov

### ISSUE THREAD

**Issue by Julnewst** [Julnewst/python-042023--Ukol1#1]
@ikopira54 Ahoj Petře, pozdě, ale snad přece. Pokud budeš mít čas se podívat i na pozdně odevzdaný úkol, budu ráda. Výsledky vyšly, ale nevím, jak se zbavit těch hlášek, kde se mu nelíbí odkaz na tabulku generovanou z původních dat. Loc mi nezafungovalo. Děkuji

**Comment by pikopira54** [comment]
ahoj, dekuji za ukol. co se tyka chyby je to jenom warning, nejjednodussi asi zmenit konfiguraci parametrem:
pd.options.mode.copy_on_write = True
hezka prace
